name: build-lagswitch

on:
  push:
  workflow_dispatch:

jobs:
  windows-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW via Chocolatey
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Build with g++
        run: |
          g++ -o lagswitch.exe main.cpp -lws2_32

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lagswitch
          path: lagswitch.exe
