name: build-lagswitch

on:
  push:
  workflow_dispatch:

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with MSVC
        shell: cmd
        run: |
          cl /EHsc /Fe:lagswitch.exe main.cpp ws2_32.lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lagswitch
          path: |
            lagswitch.exe
